server:
  port: 22333
spring:
  config:
    import:
    - application-data.yml
    - application-doc.yml
    - application-liquibase.yml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

