server:
  port: 8081
spring:
  datasource:
    username: root
    password: 5n2Qwvz0hXftUYwB
    url: jdbc:mysql://43.143.224.83:10013/dandelion?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  # redis 连接参数信息
  data:
    redis:
      jedis:
        pool:
          max-active: 100
          max-idle: 100
          max-wait: 1000
      host: 43.143.224.83
      port: 10014
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml
    database-change-log-table: databasechangelog
    database-change-log-lock-table: databasechangeloglock

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
#      packages-to-scan: com.dandelion.user.server
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
token:
  header: Authorization
  secret: dandelion
  # 过期时间 ms
  expireTime: 600000


