# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /dev/swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /dev/api-docs
    groups:
      enabled: true
    enabled: true
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
    - group: '系统管理'
      packages-to-scan:
        - 'com.dandelion.use.server.web.controller.system'
        - 'com.dandelion.use.server.web.controller.listener'
    - group: 'redis 操作'
      packages-to-scan:
        - 'com.dandelion.use.server.web.controller.redis'
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn