spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/dandelion?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  # redis 连接参数信息
  data:
    redis:
      jedis:
        pool:
          max-active: 100
          max-idle: 100
          max-wait: 1000
      host: localhost
      port: 6379


token:
  prefix: Bearer
  header: Authorization
  secret: dandelion_dev
  # 过期时间 m
  expireTime: 300

security:
  enabled: true
  excludes:
    - /webjars/**
    - /swagger-resources/**
    - /v3/api-docs/**
    - /swagger-ui/**
    - index.html
    - favicon.ico
    - doc.html
    - /api/redis/**



